a = input('Digite algo:')
print('O tipo primitivo desse valor é?', type(a))
print("é um número?", a.isnumeric())
print('Só tem espaço?', a.isspace())
print('É uma alfabédico?', a.isalpha())
print('Esta em maiuculo?', a.isupper())
print('é alfanumerico', a.isalnum())
print('Esta em minúscula',a.islower())
print('Esta capitalizada', a.istitle())
